/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminSidebar: typeof import('./src/components/layout/AdminSidebar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CalendarioHabitacion: typeof import('./src/components/pages/habitacion/calendario/CalendarioHabitacion.vue')['default']
    CalendarioReserva: typeof import('./src/components/calendar/CalendarioReserva.vue')['default']
    'Caracteristicas.web': typeof import('./src/components/pages/Caracteristicas.web.vue')['default']
    CardReservaAdmin: typeof import('./src/components/admin/CardReservaAdmin.vue')['default']
    CardReservaCliente: typeof import('./src/components/client/CardReservaCliente.vue')['default']
    ClienteNavbar: typeof import('./src/components/layout/ClienteNavbar.vue')['default']
    DescripcionHabitacion: typeof import('./src/components/pages/habitacion/reservar/DescripcionHabitacion.vue')['default']
    DescripcionReserva: typeof import('./src/components/pages/habitacion/reservar/DescripcionReserva.vue')['default']
    DrawerCliente: typeof import('./src/components/client/DrawerCliente.vue')['default']
    'EnvioCodigoOTP.web': typeof import('./src/components/pages/habitacion/reservar/EnvioCodigoOTP.web.vue')['default']
    'FinalizarReserva.web': typeof import('./src/components/pages/habitacion/reservar/FinalizarReserva.web.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    'Footer.web': typeof import('./src/components/pages/Footer.web.vue')['default']
    'Habitacion.web': typeof import('./src/components/pages/Habitacion.web.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InicioReservaHabitacion: typeof import('./src/components/pages/habitacion/reservar/InicioReservaHabitacion.vue')['default']
    LoginRegister: typeof import('./src/components/pages/habitacion/reservar/LoginRegister.vue')['default']
    LoginRegisterUsuario: typeof import('./src/components/pages/habitacion/reservar/LoginRegisterUsuario.vue')['default']
    'MetodoPago.web': typeof import('./src/components/pages/habitacion/reservar/MetodoPago.web.vue')['default']
    'Navbar.web': typeof import('./src/components/pages/Navbar.web.vue')['default']
    'Nosotros.web': typeof import('./src/components/pages/Nosotros.web.vue')['default']
    'Principal.web': typeof import('./src/components/pages/Principal.web.vue')['default']
    PublicNavbar: typeof import('./src/components/layout/PublicNavbar.vue')['default']
    RecuperarUsuario: typeof import('./src/components/layout/login/RecuperarUsuario.vue')['default']
    RegistroUsuario: typeof import('./src/components/layout/login/RegistroUsuario.vue')['default']
    'RegistroUsuario.web': typeof import('./src/components/pages/habitacion/reservar/RegistroUsuario.web.vue')['default']
    ReservaRegistrarUsuario: typeof import('./src/components/pages/habitacion/reservar/ReservaRegistrarUsuario.vue')['default']
    RestaurarPassword: typeof import('./src/components/layout/login/RestaurarPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Servicios.web': typeof import('./src/components/pages/Servicios.web.vue')['default']
    'Testimonios.web': typeof import('./src/components/pages/Testimonios.web.vue')['default']
    'VerificarNumero.web': typeof import('./src/components/pages/habitacion/reservar/VerificarNumero.web.vue')['default']
    VPhoneInput: typeof import('vuetify/lib')['VPhoneInput']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
  }
}
