/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavbar: typeof import('./src/components/layout/AdminSidebar.vue')['default']
    AdminSidebar: typeof import('./src/components/layout/AdminSidebar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CalendarioReserva: typeof import('./src/components/calendar/CalendarioReserva.vue')['default']
    'Caracteristicas.web': typeof import('./src/components/pages/Caracteristicas.web.vue')['default']
    CardReservaAdmin: typeof import('./src/components/admin/CardReservaAdmin.vue')['default']
    CardReservaCliente: typeof import('./src/components/client/CardReservaCliente.vue')['default']
    ClienteNavbar: typeof import('./src/components/layout/ClienteNavbar.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    'Footer.web': typeof import('./src/components/pages/Footer.web.vue')['default']
    'Habitacion.web': typeof import('./src/components/pages/Habitacion.web.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Login.web': typeof import('./src/components/pages/Login.web.vue')['default']
    'Navbar.web': typeof import('./src/components/pages/Navbar.web.vue')['default']
    'Nosotros.web': typeof import('./src/components/pages/Nosotros.web.vue')['default']
    'Principal.web': typeof import('./src/components/pages/Principal.web.vue')['default']
    PublicNavbar: typeof import('./src/components/layout/PublicNavbar.vue')['default']
    PublicNavBar: typeof import('./src/components/layout/PublicNavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Servicios.web': typeof import('./src/components/pages/Servicios.web.vue')['default']
    'Testimonios.web': typeof import('./src/components/pages/Testimonios.web.vue')['default']
  }
}
